sources:
  - name: raw
    database: HEALTHCARE_DB
    schema: RAW
    tables:
      - name : claims
      - name : patients
      - name : encounters
      - name : diagnoses
      - name : medications
      - name : providers